apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
type: Opaque
stringData:
  ConnectionStrings__PostgresConnection: >
    Host={{ .Values.postgres.host }};
    Port={{ .Values.postgres.port }};
    Database={{ .Values.postgres.database }};
    Username={{ .Values.postgres.username }};
    Password={{ .Values.postgres.password }}

  MINIO__ENDPOINT: {{ .Values.minio.endpoint }}
  MINIO__ACCESSKEY: {{ .Values.minio.accessKey }}
  MINIO__SECRETKEY: {{ .Values.minio.secretKey }}

  {{- if .Values.redis.enabled }}
  Redis__Connection: {{ .Values.redis.connection }}
  {{- end }}
