replicaCount: 2

image:
  repository: webapi
  pullPolicy: Never
  tag: "latest"

service:
  type: ClusterIP
  targetPort: 8080

postgres:
  host: postgres
  port: 5432

redis:
  host: redis
  port: 6379

minio:
  endpoint: minio:9000
