replicaCount: 1

image:
  repository: minio/minio
  pullPolicy: IfNotPresent
  tag: "RELEASE.2025-09-07T16-13-09Z-cpuv1"

service:
  type: ClusterIP
  port: 9000
  consolePort: 9001

buckets:
  - name: files